//
//  iFlagTriviaViewModel.swift
//  iFlagTrivia
//
//  Created by Yohannes Haile on 1/4/25.
//

class iFlagTriviaViewModel {
    
    func discoverCountries() -> [iFlag]{
        let countries = [
            iFlag(name: "Afghanistan", flag: "🇦🇫"),
            iFlag(name: "Albania", flag: "🇦🇱"),
            iFlag(name: "Algeria", flag: "🇩🇿"),
            iFlag(name: "Andorra", flag: "🇦🇩"),
            iFlag(name: "Angola", flag: "🇦🇴"),
            iFlag(name: "Antigua and Barbuda", flag: "🇦🇬"),
            iFlag(name: "Argentina", flag: "🇦🇷"),
            iFlag(name: "Armenia", flag: "🇦🇲"),
            iFlag(name: "Australia", flag: "🇦🇺"),
            iFlag(name: "Austria", flag: "🇦🇹"),
            iFlag(name: "Azerbaijan", flag: "🇦🇿"),
            iFlag(name: "Bahamas", flag: "🇧🇸"),
            iFlag(name: "Bahrain", flag: "🇧🇭"),
            iFlag(name: "Bangladesh", flag: "🇧🇩"),
            iFlag(name: "Barbados", flag: "🇧🇧"),
            iFlag(name: "Belarus", flag: "🇧🇾"),
            iFlag(name: "Belgium", flag: "🇧🇪"),
            iFlag(name: "Belize", flag: "🇧🇿"),
            iFlag(name: "Benin", flag: "🇧🇯"),
            iFlag(name: "Bhutan", flag: "🇧🇹"),
            iFlag(name: "Bolivia", flag: "🇧🇴"),
            iFlag(name: "Bosnia and Herzegovina", flag: "🇧🇦"),
            iFlag(name: "Botswana", flag: "🇧🇼"),
            iFlag(name: "Brazil", flag: "🇧🇷"),
            iFlag(name: "Brunei", flag: "🇧🇳"),
            iFlag(name: "Bulgaria", flag: "🇧🇬"),
            iFlag(name: "Burkina Faso", flag: "🇧🇫"),
            iFlag(name: "Burundi", flag: "🇧🇮"),
            iFlag(name: "Cabo Verde", flag: "🇨🇻"),
            iFlag(name: "Cambodia", flag: "🇰🇭"),
            iFlag(name: "Cameroon", flag: "🇨🇲"),
            iFlag(name: "Canada", flag: "🇨🇦"),
            iFlag(name: "Central African Republic", flag: "🇨🇫"),
            iFlag(name: "Chad", flag: "🇹🇩"),
            iFlag(name: "Chile", flag: "🇨🇱"),
            iFlag(name: "China", flag: "🇨🇳"),
            iFlag(name: "Colombia", flag: "🇨🇴"),
            iFlag(name: "Comoros", flag: "🇰🇲"),
            iFlag(name: "Congo (Congo-Brazzaville)", flag: "🇨🇬"),
            iFlag(name: "Congo (Congo-Kinshasa)", flag: "🇨🇩"),
            iFlag(name: "Costa Rica", flag: "🇨🇷"),
            iFlag(name: "Croatia", flag: "🇭🇷"),
            iFlag(name: "Cuba", flag: "🇨🇺"),
            iFlag(name: "Cyprus", flag: "🇨🇾"),
            iFlag(name: "Czechia", flag: "🇨🇿"),
            iFlag(name: "Denmark", flag: "🇩🇰"),
            iFlag(name: "Djibouti", flag: "🇩🇯"),
            iFlag(name: "Dominica", flag: "🇩🇲"),
            iFlag(name: "Dominican Republic", flag: "🇩🇴"),
            iFlag(name: "Ecuador", flag: "🇪🇨"),
            iFlag(name: "Egypt", flag: "🇪🇬"),
            iFlag(name: "El Salvador", flag: "🇸🇻"),
            iFlag(name: "Equatorial Guinea", flag: "🇬🇶"),
            iFlag(name: "Eritrea", flag: "🇪🇷"),
            iFlag(name: "Estonia", flag: "🇪🇪"),
            iFlag(name: "Eswatini", flag: "🇸🇿"),
            iFlag(name: "Ethiopia", flag: "🇪🇹"),
            iFlag(name: "Fiji", flag: "🇫🇯"),
            iFlag(name: "Finland", flag: "🇫🇮"),
            iFlag(name: "France", flag: "🇫🇷"),
            iFlag(name: "Gabon", flag: "🇬🇦"),
            iFlag(name: "Gambia", flag: "🇬🇲"),
            iFlag(name: "Georgia", flag: "🇬🇪"),
            iFlag(name: "Germany", flag: "🇩🇪"),
            iFlag(name: "Ghana", flag: "🇬🇭"),
            iFlag(name: "Greece", flag: "🇬🇷"),
            iFlag(name: "Grenada", flag: "🇬🇩"),
            iFlag(name: "Guatemala", flag: "🇬🇹"),
            iFlag(name: "Guinea", flag: "🇬🇳"),
            iFlag(name: "Guinea-Bissau", flag: "🇬🇼"),
            iFlag(name: "Guyana", flag: "🇬🇾"),
            iFlag(name: "Haiti", flag: "🇭🇹"),
            iFlag(name: "Honduras", flag: "🇭🇳"),
            iFlag(name: "Hungary", flag: "🇭🇺"),
            iFlag(name: "Iceland", flag: "🇮🇸"),
            iFlag(name: "India", flag: "🇮🇳"),
            iFlag(name: "Indonesia", flag: "🇮🇩"),
            iFlag(name: "Iran", flag: "🇮🇷"),
            iFlag(name: "Iraq", flag: "🇮🇶"),
            iFlag(name: "Ireland", flag: "🇮🇪"),
            iFlag(name: "Israel", flag: "🇮🇱"),
            iFlag(name: "Italy", flag: "🇮🇹"),
            iFlag(name: "Jamaica", flag: "🇯🇲"),
            iFlag(name: "Japan", flag: "🇯🇵"),
            iFlag(name: "Jordan", flag: "🇯🇴"),
            iFlag(name: "Kazakhstan", flag: "🇰🇿"),
            iFlag(name: "Kenya", flag: "🇰🇪"),
            iFlag(name: "Kiribati", flag: "🇰🇮"),
            iFlag(name: "Kuwait", flag: "🇰🇼"),
            iFlag(name: "Kyrgyzstan", flag: "🇰🇬"),
            iFlag(name: "Laos", flag: "🇱🇦"),
            iFlag(name: "Latvia", flag: "🇱🇻"),
            iFlag(name: "Lebanon", flag: "🇱🇧"),
            iFlag(name: "Lesotho", flag: "🇱🇸"),
            iFlag(name: "Liberia", flag: "🇱🇷"),
            iFlag(name: "Libya", flag: "🇱🇾"),
            iFlag(name: "Liechtenstein", flag: "🇱🇮"),
            iFlag(name: "Lithuania", flag: "🇱🇹"),
            iFlag(name: "Luxembourg", flag: "🇱🇺"),
            iFlag(name: "Madagascar", flag: "🇲🇬"),
            iFlag(name: "Malawi", flag: "🇲🇼"),
            iFlag(name: "Malaysia", flag: "🇲🇾"),
            iFlag(name: "Maldives", flag: "🇲🇻"),
            iFlag(name: "Mali", flag: "🇲🇱"),
            iFlag(name: "Malta", flag: "🇲🇹"),
            iFlag(name: "Marshall Islands", flag: "🇲🇭"),
            iFlag(name: "Mauritania", flag: "🇲🇷"),
            iFlag(name: "Mauritius", flag: "🇲🇺"),
            iFlag(name: "Mexico", flag: "🇲🇽"),
            iFlag(name: "Micronesia", flag: "🇫🇲"),
            iFlag(name: "Moldova", flag: "🇲🇩"),
            iFlag(name: "Monaco", flag: "🇲🇨"),
            iFlag(name: "Mongolia", flag: "🇲🇳"),
            iFlag(name: "Montenegro", flag: "🇲🇪"),
            iFlag(name: "Morocco", flag: "🇲🇦"),
            iFlag(name: "Mozambique", flag: "🇲🇿"),
            iFlag(name: "Myanmar", flag: "🇲🇲"),
            iFlag(name: "Namibia", flag: "🇳🇦"),
            iFlag(name: "Nauru", flag: "🇳🇷"),
            iFlag(name: "Nepal", flag: "🇳🇵"),
            iFlag(name: "Netherlands", flag: "🇳🇱"),
            iFlag(name: "New Zealand", flag: "🇳🇿"),
            iFlag(name: "Nicaragua", flag: "🇳🇮"),
            iFlag(name: "Niger", flag: "🇳🇪"),
            iFlag(name: "Nigeria", flag: "🇳🇬"),
            iFlag(name: "North Korea", flag: "🇰🇵"),
            iFlag(name: "North Macedonia", flag: "🇲🇰"),
            iFlag(name: "Norway", flag: "🇳🇴"),
            iFlag(name: "Oman", flag: "🇴🇲"),
            iFlag(name: "Pakistan", flag: "🇵🇰"),
            iFlag(name: "Palau", flag: "🇵🇼"),
            iFlag(name: "Palestine", flag: "🇵🇸"),
            iFlag(name: "Panama", flag: "🇵🇦"),
            iFlag(name: "Papua New Guinea", flag: "🇵🇬"),
            iFlag(name: "Paraguay", flag: "🇵🇾"),
            iFlag(name: "Peru", flag: "🇵🇪"),
            iFlag(name: "Philippines", flag: "🇵🇭"),
            iFlag(name: "Poland", flag: "🇵🇱"),
            iFlag(name: "Portugal", flag: "🇵🇹"),
            iFlag(name: "Qatar", flag: "🇶🇦"),
            iFlag(name: "Romania", flag: "🇷🇴"),
            iFlag(name: "Russia", flag: "🇷🇺"),
            iFlag(name: "Rwanda", flag: "🇷🇼"),
            iFlag(name: "Saint Kitts and Nevis", flag: "🇰🇳"),
            iFlag(name: "Saint Lucia", flag: "🇱🇨"),
            iFlag(name: "Saint Vincent and the Grenadines", flag: "🇻🇨"),
            iFlag(name: "Samoa", flag: "🇼🇸"),
            iFlag(name: "San Marino", flag: "🇸🇲"),
            iFlag(name: "Sao Tome and Principe", flag: "🇸🇹"),
            iFlag(name: "Saudi Arabia", flag: "🇸🇦"),
            iFlag(name: "Senegal", flag: "🇸🇳"),
            iFlag(name: "Serbia", flag: "🇷🇸"),
            iFlag(name: "Seychelles", flag: "🇸🇨"),
            iFlag(name: "Sierra Leone", flag: "🇸🇱"),
            iFlag(name: "Singapore", flag: "🇸🇬"),
            iFlag(name: "Slovakia", flag: "🇸🇰"),
            iFlag(name: "Slovenia", flag: "🇸🇮"),
            iFlag(name: "Solomon Islands", flag: "🇸🇧"),
            iFlag(name: "Somalia", flag: "🇸🇴"),
            iFlag(name: "South Africa", flag: "🇿🇦"),
            iFlag(name: "South Korea", flag: "🇰🇷"),
            iFlag(name: "South Sudan", flag: "🇸🇸"),
            iFlag(name: "Spain", flag: "🇪🇸"),
            iFlag(name: "Sri Lanka", flag: "🇱🇰"),
            iFlag(name: "Sudan", flag: "🇸🇩"),
            iFlag(name: "Suriname", flag: "🇸🇷"),
            iFlag(name: "Sweden", flag: "🇸🇪"),
            iFlag(name: "Switzerland", flag: "🇨🇭"),
            iFlag(name: "Syria", flag: "🇸🇾"),
            iFlag(name: "Tajikistan", flag: "🇹🇯"),
            iFlag(name: "Tanzania", flag: "🇹🇿"),
            iFlag(name: "Thailand", flag: "🇹🇭"),
            iFlag(name: "Timor-Leste", flag: "🇹🇱"),
            iFlag(name: "Togo", flag: "🇹🇬"),
            iFlag(name: "Tonga", flag: "🇹🇴"),
            iFlag(name: "Trinidad and Tobago", flag: "🇹🇹"),
            iFlag(name: "Tunisia", flag: "🇹🇳"),
            iFlag(name: "Turkey", flag: "🇹🇷"),
            iFlag(name: "Turkmenistan", flag: "🇹🇲"),
            iFlag(name: "Tuvalu", flag: "🇹🇻"),
            iFlag(name: "Uganda", flag: "🇺🇬"),
            iFlag(name: "Ukraine", flag: "🇺🇦"),
            iFlag(name: "United Arab Emirates", flag: "🇦🇪"),
            iFlag(name: "United Kingdom", flag: "🇬🇧"),
            iFlag(name: "United States", flag: "🇺🇸"),
            iFlag(name: "Uruguay", flag: "🇺🇾"),
            iFlag(name: "Uzbekistan", flag: "🇺🇿"),
            iFlag(name: "Vanuatu", flag: "🇻🇺"),
            iFlag(name: "Vatican City", flag: "🇻🇦"),
            iFlag(name: "Venezuela", flag: "🇻🇪"),
            iFlag(name: "Vietnam", flag: "🇻🇳"),
            iFlag(name: "Yemen", flag: "🇾🇪"),
            iFlag(name: "Zambia", flag: "🇿🇲"),
            iFlag(name: "Zimbabwe", flag: "🇿🇼")
        ]
        return countries
    }
    
    func generateQuestion() -> [iFlag] {
        var flagOptions = [iFlag]()
        for _ in 0...3 {
            let newOption = discoverCountries().randomElement()!
            flagOptions.append(newOption)
        }
        return flagOptions
    }
    
    func evaluateAnswer(correctAnswer: iFlag, userAnswer: String) -> Bool {
        if userAnswer == correctAnswer.flag {
            return true
        }else {
            return false
        }
    }
}
